# Generated by Django 4.1.1 on 2022-10-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
       
    ]
